# -*- coding: utf-8 -*-
"""Archive_Files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUbljoCD5QI8dKxS30sNTzU1utgHF-7y
"""

# Welcome to your new notebook
# Type here in the cell editor to add code!
from notebookutils import mssparkutils

mssparkutils.fs.help()

mssparkutils.fs.mount("abfss://bb3ae42b-617a-4d5a-baf9-d45cf59b3f04@onelake.dfs.fabric.microsoft.com/ff98c3a6-7203-438e-b395-a08c628364e2/Files","/Files")

mssparkutils.fs.getMountPath("/Files")

check_files=mssparkutils.fs.ls(f"file://{mssparkutils.fs.getMountPath('/Files')}/Current/")

for file in check_files:
    if file.path:
        mssparkutils.fs.mv(file.path,f"file://{mssparkutils.fs.getMountPath('/Files')}/Archive/")

