# -*- coding: utf-8 -*-
"""Gold_Product.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vVMGbjatVuOBSbYwdvh41YSKtyeNvuaL
"""

# Welcome to your new notebook
# Type here in the cell editor to add code!
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# create table if not EXISTS Project_Lakehouse.gold_product
# (
#    Product_ID long,
#    Product_Category string,
#    Product string,
#    Created_TS timestamp,
#    Modified_TS timestamp
# )
# USING DELTA

Max_Date = spark.sql("""
SELECT coalesce(max(Modified_TS),'1990-01-01') FROM Project_Lakehouse.gold_product
""").first()[0]

Max_Date

df_bronze = spark.sql("""
SELECT distinct Product_Category, Product
FROM Project_Lakehouse.bronze_sales WHERE Modified_TS>'{}'
""".format(Max_Date))

Max_ID=spark.sql("select coalesce(max(Product_ID),'0') from Project_Lakehouse.gold_product").first()[0]

df_final = df_bronze.withColumn("Product_ID",monotonically_increasing_id()+Max_ID+1)

df_final.createOrReplaceTempView("ViewProduct")

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# MERGE INTO Project_Lakehouse.gold_product AS gp
# USING ViewProduct AS vp
# ON gp.Product = vp.Product
#    AND gp.Product_Category = vp.Product_Category
# WHEN MATCHED THEN
#     UPDATE SET
#         gp.Modified_TS = CURRENT_TIMESTAMP()
# WHEN NOT MATCHED THEN
#     INSERT (
#         Product_ID,
#         Product_Category,
#         Product,
#         Created_TS,
#         Modified_TS
#     )
#     VALUES (
#         vp.Product_ID,
#         vp.Product_Category,
#         vp.Product,
#         CURRENT_TIMESTAMP(),
#         CURRENT_TIMESTAMP()
#     )
#