# -*- coding: utf-8 -*-
"""Gold_OrderReturn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18UNGB_JDJpITLbF8yGXWwP2whBCbLSjo
"""

from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# create table if not exists Project_Lakehouse.Gold_OrderReturn
# (
# 
# Order_ID  string,
# Return string,
# Order_Year int,
# Order_Month int,
# Created_TS TIMESTAMP,
# Modified_TS TIMESTAMP
# 
# )
# using delta
# partitioned by(Order_Year,Order_Month)

Max_Date=spark.sql("select coalesce(max(Modified_TS),'1900-01-01') from Project_Lakehouse.gold_orderreturn").first()[0]

Max_Date

df=spark.sql("""select Order_ID  ,
Return ,
Order_Year,
Order_Month ,
Created_TS ,
Modified_TS
from Project_Lakehouse.bronze_sales where Return="Yes" and Modified_TS>'{}'""".format(Max_Date))

df.createOrReplaceTempView("ViewReturn")

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# insert into Project_Lakehouse.gold_orderreturn
# select * from ViewReturn

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * from Gold_OrderReturn limit 10