# -*- coding: utf-8 -*-
"""Gold_Date.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJ7VCJ9GraDC9UfxX1hE4MgTeiqpD0Dv
"""

# Welcome to your new notebook
# Type here in the cell editor to add code!
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# create table if not EXISTS Project_Lakehouse.gold_date
# (
# BusinessDate Date,
# Business_Year int,
# Business_Month int,
# Business_Quarter int,
# Business_Week int
# )
# using DELTA
# PARTITIONED by (Business_Year)

start_date='2015-01-01'
end_date='2030-12-31'

date_diff=spark.sql("select date_diff('{}','{}')".format(end_date,start_date)).first()[0]

date_diff

ID_Data=spark.range(0,date_diff)

date_data=ID_Data.selectExpr("date_add('{}',cast(id as int)) as BusinessDate".format(start_date))

date_data.createOrReplaceTempView("ViewDate")

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# delete from Project_Lakehouse.gold_date;
#

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# insert into Project_Lakehouse.gold_date
# select *,
# Year(BusinessDate) as Business_Year,
# Month(BusinessDate) as Business_Month,
# Quarter(BusinessDate) as Business_Quarter,
# weekday(BusinessDate) as Business_Week
#  from ViewDate

