# -*- coding: utf-8 -*-
"""Gold_Customer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lIKSE6c1QOKFmz8e7iWy2PC0cPWRiNCP
"""

# Welcome to your new notebook
# Type here in the cell editor to add code!
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# create table if not exists Project_Lakehouse.gold_Customer
# (
#   Customer_ID	string	,
# Customer_Name	string	,
# Segment	string	,
# City	string	,
# State	string	,
# Country	string	,
# Region	string	,
# Created_TS	timestamp	,
# Modified_TS	timestamp
# 
# )
# using delta

Max_Date=spark.sql("""select coalesce(max(Modified_TS),"1900-01-01") from Project_Lakehouse.gold_Customer""").first()[0]

Max_Date

df_bronze=spark.read.table("Project_Lakehouse.bronze_sales")

df_final=df_bronze.selectExpr("Customer_ID","Customer_Name","Segment","City","State", \
                   "Country","Region")\
                   .where(col("Modified_TS")>Max_Date)\
                   .drop_duplicates()

df_final.createOrReplaceTempView("ViewCustomer")

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# Merge into Project_lakehouse.gold_customer as gc
# using ViewCustomer as vc
# on gc.Customer_ID=vc.Customer_ID
# when matched then
# update set
# gc.Customer_Name	=	vc.Customer_Name	,
# gc.Segment	=	vc.Segment	,
# gc.City	=	vc.City	,
# gc.State	=	vc.State	,
# gc.Country	=	vc.Country	,
# gc.Region	=	vc.Region	,
# gc.Modified_TS	=	current_timestamp()
# 
# when not matched then insert
# (
# gc.Customer_ID	,
# gc.Customer_Name	,
# gc.Segment	,
# gc.City	,
# gc.State	,
# gc.Country	,
# gc.Region	,
# gc.Created_TS	,
# gc.Modified_TS
# )
# values
# (
# vc.Customer_ID	,
# vc.Customer_Name	,
# vc.Segment	,
# vc.City	,
# vc.State	,
# vc.Country	,
# vc.Region	,
# current_timestamp(),
# current_timestamp
# )

