# -*- coding: utf-8 -*-
"""Gold_ShipMode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wh-o9U4VRrc1Og6f_IWD0IO6dgIx9oeN
"""

# Welcome to your new notebook
# Type here in the cell editor to add code!
from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# create table if not exists Project_Lakehouse.gold_shipmode
# (
#     ShipMode_ID	Long	,
# Ship_Mode	string	,
# Created_TS	timestamp,
# Modified_TS timestamp
# )

Max_Date=spark.sql("select coalesce(max(Modified_TS),'1900-01-01') from Project_Lakehouse.gold_shipmode").first()[0]

Max_Date

df_bronze=spark.sql("select distinct Ship_Mode from Project_Lakehouse.bronze_sales where Modified_TS>'{}'".format(Max_Date))

Max_ID=spark.sql("select coalesce(max(ShipMode_ID),0) from Project_Lakehouse.gold_shipmode").first()[0]

df_final=df_bronze.withColumn("ShipMode_ID",monotonically_increasing_id()+Max_ID+1)
df_final.createOrReplaceTempView("ViewShipMode")

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# merge into Project_Lakehouse.gold_shipmode as gs
# using ViewShipMode as vs
# on gs.Ship_Mode=vs.Ship_Mode
# when MATCHED then
# update set
# Modified_TS= current_timestamp()
# 
# when not matched then
# INSERT
# (
# gs.ShipMode_ID,
# gs.Ship_Mode,
# gs.Created_TS,
# gs.Modified_TS
# )
# VALUES
# (
# vs.ShipMode_ID,
# vs.Ship_Mode,
# current_timestamp(),
# current_timestamp()
# 
# )
# 
#

